/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.65
 * Generated at: 2022-09-18 08:28:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import com.hit.utility.DBUtil;
import javax.servlet.annotation.WebServlet;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("javax.servlet.annotation.WebServlet");
    _jspx_imports_classes.add("com.hit.utility.DBUtil");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			"errorpage.jsp", true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write(" \r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("  <head>\r\n");
      out.write("    <link rel=\"shortcut icon\" type=\"image/png\" href=\"images/logo.png\">\r\n");
      out.write("    <!--link rel=\"shortcut icon\" type=\"image/ico\" href=\"images/hit_fevicon.ico\"-->\r\n");
      out.write("	\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Tender Management System</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/bootstrap.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/annimate.css\">\r\n");
      out.write("    <link href=\"css/font-awesome.min.css\" type=\"text/css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"css/SpryTabbedPanels.css\" type=\"text/css\" rel=\"stylesheet\">\r\n");
      out.write("    <!--link rel=\"stylesheet\" href=\"css/styles.css\"-->\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css?family=Black+Ops+One\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"css/bootstrap-dropdownhover.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/style2.css\">\r\n");
      out.write("    <style>\r\n");
      out.write("	.tab{\r\n");
      out.write("	border-radius:1px;\r\n");
      out.write("		border:1px black solid;\r\n");
      out.write("		background-color: #FFE5CC;\r\n");
      out.write("		margin-left: 25%;\r\n");
      out.write("		width:450px;\r\n");
      out.write("		color:green;\r\n");
      out.write("		font-weight: bold;\r\n");
      out.write("		font-style:normal;\r\n");
      out.write("		text-align:center;\r\n");
      out.write("		font-size: 20px;\r\n");
      out.write("		margin-bottom:10px;\r\n");
      out.write("		padding:20px;\r\n");
      out.write("	}\r\n");
      out.write("    </style>\r\n");
      out.write("  </head>\r\n");
      out.write("<body>\r\n");
      out.write("	<!-- Including the header of the page  -->\r\n");
      out.write("	\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "loginHeader.jsp", out, false);
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "menu.jsp", out, false);
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	<div class=\"clearfix hidden-sm hidden-xs\" style=\"color:white;background-color: green; margin-top:-15px; margin-bottom: 12px\"><marquee>Welcome to Tender Management System</marquee>\r\n");
      out.write(" </div> <!--A green color line between header and body part-->\r\n");
      out.write(" \r\n");
      out.write("     <div class=\"container-fluid\">\r\n");
      out.write("     \r\n");
      out.write("     	<div class=\"notice\">\r\n");
      out.write("        <div class=\"col-md-3\"style=\"margin-left:2%\">\r\n");
      out.write("     		");
 Connection con = DBUtil.provideConnection(); 
      out.write("\r\n");
      out.write("     		\r\n");
      out.write("     		");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "notice.jsp", out, false);
      out.write("<br>\r\n");
      out.write("     		\r\n");
      out.write("          <!-- Next marquee starting-->\r\n");
      out.write("          ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "approved.jsp", out, false);
      out.write("<br>\r\n");
      out.write("          \r\n");
      out.write("        </div>  <!-- End of col-md-3-->\r\n");
      out.write("      </div> <!-- End of notice class-->\r\n");
      out.write("     \r\n");
      out.write("        <div class=\"header\">\r\n");
      out.write("  <h2>Account login</h2>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"headerfor\">\r\n");
      out.write(" <p id=\"show\"></p>\r\n");
      out.write("	</div>\r\n");
      out.write("      \r\n");
      out.write("	<div class=\"cardStyle\">\r\n");
      out.write("	<form action=\"LoginSrv\" method=\"post\">\r\n");
      out.write("	<div class=\"inputDiv\">\r\n");
      out.write("      <label class=\"inputLabel\" for=\"password\">Username:</label>\r\n");
      out.write("      <input type=\"text\" name=\"username\" required>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"inputDiv\">\r\n");
      out.write("      <label class=\"inputLabel\" for=\"password\">Enter Password:</label>\r\n");
      out.write("      <input type=\"password\" type=\"password\" name=\"password\" required>\r\n");
      out.write("    </div>\r\n");
      out.write("        \r\n");
      out.write("    <div class=\"buttonWrapper\">\r\n");
      out.write("      <button type=\"submit\" value=\"Login As Vendor\" name=\"user\" class=\"submitButton pure-button pure-button-primary\">Login As Vendor</button>\r\n");
      out.write("      <button type=\"submit\" value=\"Login As Admin\" name=\"user\" class=\"submitButton pure-button pure-button-primary\">Login As Admin</button>\r\n");
      out.write("    </div>\r\n");
      out.write("      \r\n");
      out.write("  </form>\r\n");
      out.write("</div>\r\n");
      out.write("      </div>\r\n");
      out.write("     </div>\r\n");
      out.write("     </div>\r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("    </div> <!-- End of container-fluid-->\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "footer.jsp", out, false);
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write(" .header {\r\n");
      out.write("        border-radius: 40px;\r\n");
      out.write("    text-underline-offset: auto;\r\n");
      out.write("    padding: 5px;\r\n");
      out.write("    background: #33544d;\r\n");
      out.write("    color: white;\r\n");
      out.write("    font-size: 30px;\r\n");
      out.write("    position: relative;\r\n");
      out.write("    font-family: cursive;\r\n");
      out.write("    top: 20px;\r\n");
      out.write("    left: 391px;\r\n");
      out.write("    width: 60%;\r\n");
      out.write("    margin: auto;\r\n");
      out.write("    text-align: -webkit-match-parent;\r\n");
      out.write("    margin-left: 0px;\r\n");
      out.write("}\r\n");
      out.write(".headerfor {\r\n");
      out.write("   padding: 10px;\r\n");
      out.write("    background: #12bc98;\r\n");
      out.write("    color: white;\r\n");
      out.write("    font-size: 20px;\r\n");
      out.write("    position: relative;\r\n");
      out.write("    font-family: cursive;\r\n");
      out.write("    top: 70px;\r\n");
      out.write("    width: 40%;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    margin: auto;\r\n");
      out.write("    margin-right: 255px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".mainDiv {\r\n");
      out.write("    display: flex;\r\n");
      out.write("    min-height: 100%;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("    justify-content: center;\r\n");
      out.write("    background-color: #f9f9f9;\r\n");
      out.write("    font-family: 'Open Sans', sans-serif;\r\n");
      out.write("  }\r\n");
      out.write(" .cardStyle {\r\n");
      out.write("  \r\n");
      out.write("       width: 500px;\r\n");
      out.write("    border-color: white;\r\n");
      out.write("    background: #fff;\r\n");
      out.write("    padding: 36px 0;\r\n");
      out.write("    border-radius: 15px;\r\n");
      out.write("    margin: 30px 0;\r\n");
      out.write("    box-shadow: 0px 0 2px 0 rgb(0 0 0 / 25%);\r\n");
      out.write("    display: flex;\r\n");
      out.write("    min-height: 100%;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("    justify-content: center;\r\n");
      out.write("    padding: 100p;\r\n");
      out.write("    position: relative;\r\n");
      out.write("    left: 150px;\r\n");
      out.write("    top: 80px;\r\n");
      out.write("  }\r\n");
      out.write("#signupLogo {\r\n");
      out.write("  max-height: 100px;\r\n");
      out.write("  margin: auto;\r\n");
      out.write("  display: flex;\r\n");
      out.write("  flex-direction: column;\r\n");
      out.write("}\r\n");
      out.write(".formTitle{\r\n");
      out.write("  font-weight: 600;\r\n");
      out.write("  margin-top: 20px;\r\n");
      out.write("  color: #2F2D3B;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("}\r\n");
      out.write(".inputLabel {\r\n");
      out.write("  font-size: 12px;\r\n");
      out.write("  color: #555;\r\n");
      out.write("  margin-bottom: 6px;\r\n");
      out.write("  margin-top: 24px;\r\n");
      out.write("}\r\n");
      out.write("  .inputDiv {\r\n");
      out.write("        width: 100%;\r\n");
      out.write("    display: flex;\r\n");
      out.write("    flex-direction: column;\r\n");
      out.write("    margin: auto;\r\n");
      out.write("  }\r\n");
      out.write("input {\r\n");
      out.write("  height: 40px;\r\n");
      out.write("  font-size: 16px;\r\n");
      out.write("  border-radius: 4px;\r\n");
      out.write("  border: none;\r\n");
      out.write("  border: solid 1px #ccc;\r\n");
      out.write("  padding: 0 11px;\r\n");
      out.write("      width: 350px;\r\n");
      out.write("}\r\n");
      out.write("input:disabled {\r\n");
      out.write("  cursor: not-allowed;\r\n");
      out.write("  border: solid 1px #eee;\r\n");
      out.write("}\r\n");
      out.write(".buttonWrapper {\r\n");
      out.write("  margin-top: 40px;\r\n");
      out.write("}\r\n");
      out.write("  .submitButton {\r\n");
      out.write("        width: 70%;\r\n");
      out.write("    height: 40px;\r\n");
      out.write("    margin: auto;\r\n");
      out.write("    display: block;\r\n");
      out.write("    color: #fff;\r\n");
      out.write("    background-color: #065492;\r\n");
      out.write("    border-color: #065492;\r\n");
      out.write("    text-shadow: 0 -1px 0 rgb(0 0 0 / 12%);\r\n");
      out.write("    box-shadow: 0 2px 0 rgb(0 0 0 / 4%);\r\n");
      out.write("    border-radius: 4px;\r\n");
      out.write("    font-size: 14px;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("    width: 200px;\r\n");
      out.write("    margin: 0 auto;\r\n");
      out.write("    display: inline;\r\n");
      out.write("  }\r\n");
      out.write(".submitButton:disabled,\r\n");
      out.write("button[disabled] {\r\n");
      out.write("  border: 1px solid #cccccc;\r\n");
      out.write("  background-color: #cccccc;\r\n");
      out.write("  color: #666666;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#loader {\r\n");
      out.write("  position: absolute;\r\n");
      out.write("  z-index: 1;\r\n");
      out.write("  margin: -2px 0 0 10px;\r\n");
      out.write("  border: 4px solid #f3f3f3;\r\n");
      out.write("  border-radius: 50%;\r\n");
      out.write("  border-top: 4px solid #666666;\r\n");
      out.write("  width: 14px;\r\n");
      out.write("  height: 14px;\r\n");
      out.write("  -webkit-animation: spin 2s linear infinite;\r\n");
      out.write("  animation: spin 2s linear infinite;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
